#
# Dit is de configuratie voor de ATOM-LITE ESP32 Blueutooth Proxy
# 
#  Als eerste definieer variabelen om zo deze code te kunnen hergebruiken.
#
substitutions:

  device_name: "atom-woonkamer"
  friendly_name: Atom-Woonkamer


<<: !include includes/atom-lite-bt.yaml

