#
# Dit is de configuratie voor de ATOM-LITE ESP32 Blueutooth Proxy
# 
#  Als eerste definieer variabelen om zo deze code te kunnen hergebruiken.
#
substitutions:

  device_name: "atom-woonkamer-2"
  internal_name: "Woonk-Airco"
  friendly_name: Airco

<<: !include includes/atom-lite-bt.yaml
#<<: !include includes/atom-lite-climate.yaml
