substitutions:
  name: m5stack-atom-lite-2392b8
  friendly_name: Bluetooth Proxy Woonkamer
packages:
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/m5stack/m5stack-atom-lite.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: v9K0iBIa/oVC1LTFMwdolbWIfmqIDRCz3KhoA6rSdfw=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
